<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file C:\workspace\downloadvar\dev\db\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'downloa3_downloadvar' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=downloa3_downloadvar',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'downloa3_downloadvar',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-downloadvar-conf.php');
return $conf;